import torch
import numpy as np
import faiss
import pickle
import requests
import os
from dotenv import load_dotenv
from transformers import DPRQuestionEncoder, DPRQuestionEncoderTokenizer
import warnings

# Disable warnings for a cleaner terminal output
warnings.filterwarnings('ignore')

# Load environment variables from .env file
load_dotenv()

# =========================================================================
# ⚙️ CLOUDFLARE WORKERS AI CONFIGURATION (FROM .ENV FILE)
# =========================================================================
CF_ACCOUNT_ID = os.getenv("CF_ACCOUNT_ID")
CF_API_TOKEN =  os.getenv("CF_API_TOKEN")
CF_MODEL_ID =   os.getenv("CF_MODEL_ID", "@cf/meta/llama-3-8b-instruct")
# =========================================================================

def search_relevant_contexts(question, question_tokenizer, question_encoder, index, k=3):
    """
    Search mechanism: Encodes the user's question, searches the FAISS index to retrieve the top 3 relevant paragraphs.
    """
    question_inputs = question_tokenizer(question, return_tensors='pt')
    with torch.no_grad():
        question_embedding = question_encoder(**question_inputs).pooler_output.detach().numpy()
    D, I = index.search(question_embedding, k)
    return D, I

def generate_answer_cloudflare(question, contexts):
    """
    Sends an API request to Cloudflare's Llama-3 to generate the answer instead of running GPT-2 locally.
    """
    # 1. Protect against missing API Keys
    if not CF_ACCOUNT_ID or not CF_API_TOKEN or "insert_account_id" in CF_ACCOUNT_ID:
        return "⚠️ ERROR: You must fill in the Account ID and API Token in the .env file before chatting!"

    # 2. Format the context texts
    context_str = "\n".join(contexts)
    prompt = f"Context information from company handbook:\n{context_str}\n\nGiven the context above, strictly answer the question: {question}"

    # 3. Create the HTTP Request
    url = f"https://api.cloudflare.com/client/v4/accounts/{CF_ACCOUNT_ID}/ai/run/{CF_MODEL_ID}"
    headers = {
        "Authorization": f"Bearer {CF_API_TOKEN}",
        "Content-Type": "application/json"
    }
    
    # 4. Prepare the Payload (System and User messages)
    data = {
        "messages": [
            {"role": "system", "content": "You are a professional HR assistant. Answer accurately based ONLY on the provided context. Make the answer natural, concise and directly related to the question."},
            {"role": "user", "content": prompt}
        ]
    }
    
    try:
        response = requests.post(url, headers=headers, json=data)
        response.raise_for_status() # Raise exception for invalid HTTP responses (e.g. 401 Unauthorized)
        result = response.json()
        
        # Extract the exact response string generated by Llama-3
        return result['result']['response'].strip()
    except Exception as e:
        return f"⚠️ Cloudflare API Error: {str(e)}"

def main():
    print("[1/3] Loading Vector Database from local storage...")
    try:
        index = faiss.read_index('company_policies.faiss')
        with open('paragraphs_list.pkl', 'rb') as f:
            paragraphs = pickle.load(f)
    except FileNotFoundError:
        print("❌ Error: Database not found! Please run build_db.py first.")
        return

    print("[2/3] Loading Retriever (DPR Question Encoder)...")
    question_encoder = DPRQuestionEncoder.from_pretrained('facebook/dpr-question_encoder-single-nq-base')
    question_tokenizer = DPRQuestionEncoderTokenizer.from_pretrained('facebook/dpr-question_encoder-single-nq-base')

    print("[3/3] Establishing connection to CLOUDFLARE AI WORKERS...")
    if not CF_ACCOUNT_ID or "dán_account_id" in CF_ACCOUNT_ID:
        print("\n⏳ WARNING: Do not forget to fill in CF_ACCOUNT_ID and API Token in your .env file!")

    print("\n" + "="*50)
    print("🚀 SUPER RAG SYSTEM (Powered by Cloudflare Llama-3) IS READY!")
    print("="*50)
    
    while True:
        question = input("\n👤 Your Question: ")
        if question.lower().strip() in ['quit', 'exit']:
            break
            
        print("⏳ Searching documents and querying Cloudflare Llama-3...")
        
        # 1. Retrieve Context
        distances, indices = search_relevant_contexts(question, question_tokenizer, question_encoder, index, k=3)
        retrieved_contexts = [paragraphs[idx] for idx in indices[0]]
        
        # 2. Get Llama-3's answer via REST API
        answer = generate_answer_cloudflare(question, retrieved_contexts)
        
        # 3. Output the UI
        print("\n" + "-"*50)
        print("🤖 Cloudflare RAG Answer: ")
        print(answer)
        print("\n[Extracted from Company Policies Document]:")
        for i, ctx in enumerate(retrieved_contexts):
            print(f"- {ctx}")
        print("-"*50)

if __name__ == "__main__":
    main()
